
name: Maven Build

on:
  pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [21]
    runs-on: ${{ matrix.os }}
    steps:
      # Check out Git repository
      - uses: actions/checkout@v5

      # Check out Git repository
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          architecture: x64
          cache: maven

      - name: mvn verify cf-smoke
        run: mvn --batch-mode -f cf-smoke/pom.xml clean verify

      - name: mvn verify smoke
        run: mvn --batch-mode -f smoke/pom.xml clean verify

      - name: mvn verify wcm-smoke
        run: mvn --batch-mode -f wcm-smoke/pom.xml clean verify

      - name: mvn verify xf-smoke
        run: mvn --batch-mode -f xf-smoke/pom.xml clean verify

      - name: mvn verify ui-cypress
        run: mvn --batch-mode -f ui-cypress/pom.xml clean verify

      - name: mvn verify ui-playwrigh
        run: mvn --batch-mode -f ui-playwright/pom.xml clean verify

      - name: mvn verify ui-selenium-webdriver
        run: mvn --batch-mode -f ui-selenium-webdriver/pom.xml clean verify

      - name: mvn verify ui-selenium-webdriver
        run: mvn --batch-mode -f ui-selenium-webdriver/test-module/pom.xml clean verify

      - name: mvn verify ui-wdio
        run: mvn --batch-mode -f ui-wdio/pom.xml clean verify
